### ISSUE TITLE
RFC: Rename the Artsy Omakase to [Something]

### ISSUE THREAD

**Issue by orta** [artsy/README#10]
## Proposal:

Take the Artsy Omakase ([vid](https://vimeo.com/260417482#t=1260s) [vid2](https://www.youtube.com/watch?v=1Z3loALSVQM)):

- React / React Native
- TypeScript 
- Relay
- GraphQL
- Jest
- Styled Components
- Storybooks
- VS Code

and give it a name. 

## Reasoning

We always have to explain the word omakase. It totally fits, yeah, and it [references ruby on rails](http://david.heinemeierhansson.com/2012/rails-is-omakase.html) In a way I particularly enjoy. Yet, it's better that we can give the stack a real name rather than a referential one.

Studio reflects the idea that it's a setting / place for getting things done. Which kinda fits how we settled on this stack. We didn't create any of these major projects, but our studio is where we got them all to work really well with each other to help keep it focused. 

I think once named from “the artsy omakase” we can do:

1. a consolidated docs site, for internal and external use
2. a CLI for quickly creating particular components trivially (and maybe bootstrapping projects)
3. have a way to debate/discuss the core deps (e.g. is react-tracking in there?)

## Ideas

- Studio is/was the forerunner
- Palette would have been a good name, but taken for the design system
- Easel/Mural are also great names for the past framework-y names
- There was a debate about `ohm` / `Ω` as a reference to omakase, but we have a private repo call ohm, and that's gonna be confusing

## Additional Context:

[Older slack discussion](https://artsy.slack.com/archives/C2TQ4PT8R/p1534350702000100)

**Comment by alloy** [comment]
I like it 👍

**Comment by mbilokonsky** [comment]
My only hangup with "Artsy Studio" is that as a New Yorker a studio just sounds like a tiny overpriced room to sleep in.

It took me a while to wrap my head around how omakase was different from a stack, and I realized that it's because what Omakase describes isn't actually a noun - it's a collection of related verbs. It's not just these technologies but the way they are intertwined, right?

I don't wanna derail if this is more-or-less a done deal, but I keep coming back to something like "The Artsy Way" or "The Dao of Artsy" or something in that vein, something dynamic and fluid. Artsy Studio feels immediately sort of dated, to me, like there's an implicit 1.0 hanging off of it in a very 1997 font?

But, take this with a grain of salt, obviously, just my two cents!

**Comment by damassi** [comment]
"Studio" feels too much like "Dreamweaver Studio" or "Flash Studio" or like "X Studio" -- like... appending "Studio" to a group of things is too often the default fallback for orgs and apps and businesses. Artsy Omakase feels creative and unique, even if it might not capture the full spectrum of what you're trying to describe and is a bit annoying to define. 

Rather than RFC'ing a change to a single name, we should come up with a group of names and narrow it down to a vote. Def down with changing from Omakase, but I think we can come up with some other alternatives to Studio!

**Comment by orta** [comment]
I'm happy to have this be "re-name the omakase" thread, Ohm and Studio were the result of a bunch of chats at offsite etc 👍 

I'm definitely not stuck with it though, so I've updated the PR ^

> "Dreamweaver Studio" or "Flash Studio" 

Hah 🥇 

>  "The Artsy Way" or "The Dao of Artsy"

If it ends up being something that vague, we'd be better off sticking with the Omakase IMO - but I'd like the name to have clarity and ideally be a single word.

**Comment by mbilokonsky** [comment]
The Artsy Approach, Artsy Under the Hood, Artsy Craftsy (I'll see myself out)

**Comment by orta** [comment]
Can people come up with better names? I've not found anything else useful in the time in-between and I've have had a few watercolor conversations in the office on the topic now.

**Comment by damassi** [comment]
Heh -- I really like `Artsy Omakase` ;) Its weird and though it requires some explaination its a useful concept. It also looks cool to read

**Comment by orta** [comment]
Hah - I'm definitely open to just saying 'we stick with omakase' and make it werq.

If folks are in agreement, want to 👍 on this or the above comment?

**Comment by alloy** [comment]
I do like Omakase over Studio.

**Comment by anandaroop** [comment]
I actually liked Studio bc I thought it fit Artsy's domain well (despite being a somewhat hackneyed default name for many other projects, as pointed out above.)

Omakase will have the benefit(?) of [resonating with Rails people](http://david.heinemeierhansson.com/2012/rails-is-omakase.html), but might also be seen as derivative for that same reason.

I'm fine with either really. 

(Though it does occur to me that there are other Japanese terms which are about aesthetics and that are painfully apt: _wabi-sabi_, _mono no aware_, etc. Not sure if they make for good names though 😅 )

Ok, one last suggestion from the peanut gallery: Artsy Mold, as in what sculptors may use:

![screen shot 2018-09-10 at 9 47 08 am](https://user-images.githubusercontent.com/140521/45301238-88766500-b4de-11e8-8f36-18d6b0b6255d.png)

**Comment by orta** [comment]
For me the rails reference was something I was explicitly aiming for when I first started using the term. I don't feel it's in our interest to try go all out and actually make a rails-like framework for JS with that name etc, but the central theme of that blog post (outside of the dealings with folk) really resonates with what we ended up creating.

Also, you are definitely not the peanut gallery man 🥇 

Interesting, "Artsy Wabi-Sabi" does have a nice phonetic sound and really does hit home on the ideas of the stack too - damnit, now I feel a bit more conflicted

> In traditional Japanese aesthetics, wabi-sabi (侘寂) is a world view centered on the acceptance of transience and imperfection.[2] The aesthetic is sometimes described as one of beauty that is "imperfect, impermanent, and incomplete".[3] It is a concept derived from the Buddhist teaching of the three marks of existence (三法印 sanbōin), specifically impermanence (無常 mujō), suffering (苦 ku) and emptiness or absence of self-nature (空 kū).

**Comment by orta** [comment]
OK, I'm calling this. Omakase is sticking around for good 🍣🥇
