### ISSUE TITLE
[RFC] Document the rationale for why Artsy's various closed source repositories aren't open

### ISSUE THREAD

**Issue by ashfurrow** [artsy/README#131]
## Proposal

Document the rationale for why Artsy's various closed source repositories aren't open in their respective readmes.

## Reasoning

Artsy Engineering defines [Open Source by Default](https://github.com/artsy/README/blob/master/culture/engineering-principles.md#open-source-by-default) as its _first_ Engineering Guiding Principle. Consequently, _closed_ source projects are – in a sense – an exception. As engineers, we generally try to document exceptions and edge cases, and so documenting why a certain repo is closed would be congruent with our documentation practices.

This would introduce a slight bit of friction when creating new repositories, forcing engineers to consider why or why not a repo should be closed. This also lets Artsy Engineering revisit the decision to close a project if and when circumstances change.

Some examples of rationales:

- **[Gravity](https://github.com/artsy/gravity)** is closed because the data entity modelling exposes details of Artsy's business that make us unique and valuable.
- **[Osmosis](https://github.com/artsy/osmosis/)** is [closed because](https://github.com/artsy/osmosis/issues/45) we'd be discussing details of how strictly to interpret our various privacy/GDPR obligations and when/how to implement specific things, which feels unsafe to do in public.

## Exceptions:

I can't think of any exceptions to this. The rationales would, definitionally, be secret, so there's no real risk. We could always whitelist individual repos from this requirement as we come across them.

## Additional Context:

We can probably include this in the repo's `meta` section and enforce it with Peril. See [this issue](https://github.com/artsy/peril-settings/issues/29) for more context around `meta` sections.

## How is this RFC resolved?

A PR to peril-settings adding the check, run periodically.

**Comment by orta** [comment]
Oh, this is a lovely idea!

**Comment by jonallured** [comment]
I think this is a fantastic idea!!

**Comment by ashfurrow** [comment]
## Resolution
We decided to do it.

## Level of Support
2: Positive feedback.

#### Additional Context:
None.

## Next Steps
I will implement a Peril rule.

#### Exceptions
None.

**Comment by ashfurrow** [comment]
Going to re-open this as a reminder to implement the Peril rule.

**Comment by izakp** [comment]
Fwiw, concerning our configuration-as-code infrastructure repos:
[Substance](https://github.com/artsy/substance) and [Infrastructure](https://github.com/artsy/infrastructure) are comprised mostly of [Terraform](https://www.terraform.io/) templates that define our particular cloud setup, and not code that has any value in sharing.

**Comment by jonallured** [comment]
@izakp gotcha, so for those repos you'd just have a line in the README that explains why they aren't open and the check would pass. This RFC is mostly about pushing us to articulate why things are closed, certainly not to open things that shouldn't be!

Having said that, we don't open source stuff just because we think sharing it with others has value but also because working in the open has it's own advantages to Artsy. Unless there's clear business value in having a repo closed, defaulting to open is the guidance.

I don't know much about Substance, Infrastructure or Terraform and trust you to make the call here, but feel free to open things simply for the sake of opening them! I have found working in the open quite liberating. I don't think anyone outside Artsy will ever contribute to [Bearden](https://github.com/artsy/bearden), for example, but I was able to do a talk at my local Ruby meetup where I showed some cool stuff in there. I could show code examples and encourage the group to explore the repo because it was open - things I wouldn't have been able to do if it was closed!

I believe the advantages to Artsy's engineering brand for us working in the open are huge. Anyway, just wanted to chime in, now back to actually implementing this sucker! 😝 

https://github.com/artsy/peril-settings/pull/96

**Comment by alloy** [comment]
Tagging on to @jonallured’s comment above, one of _my_ personal faves for OSS'ing code only you may be using is so that you can refer back to it in a future job with a different employer. Such as [this example](
https://github.com/artsy/exchange/pull/377#discussion_r251818406) where we ended up drawing from code I wrote a decade ago.

**Comment by izakp** [comment]
My point is that Substance and Infrastructure are 90% configuration pertaining to our cloud configuration, and it's been in my experience best practice from an operational security standpoint not to leak particulars about our potential attack surfaces (open ports, etc) when it comes to our running infrastructure.  I would much prefer we do a security audit than taking the open source by default approach when it comes to cloud configuration.

When it comes to our own code, on the other hand I see all your points raised here.  So the exceptions in these repos would be [Chef cookbooks in the infrastructure repo](https://github.com/artsy/infrastructure/tree/master/site-cookbooks), and some custom scripts around orchestrating Kubernetes provisioning in [Substance](https://github.com/artsy/substance/blob/master/manage.py)
