### ISSUE TITLE
[RFC] Provide explicit recommendations when PDDE should take time off

### ISSUE THREAD

**Issue by zephraph** [artsy/README#171]
## Proposal:

Provide explicit recommendations in the PDDE playbook for when employees _should_ take time off. Situations like high stress or after hours work. 

A time off recommendation may be something like:

- After dealing with an overnight on-call incident, take the next possible day off. 
- After dealing with a high-stress on-call rotation, add two days to your weekend.
- When dealing with a sustained push to meet a product deadline (i.e. local discovery) take a week to recoup

_These are just examples_.

## Reasoning

At Artsy we believe **people are paramount**. We generally have a healthy appreciation for work life balance. Leadership often encourages people to take a little time to recharge after they've put in a lot of effort. There's almost a mantra to managers for them to tell their direct reports to take time off. It's a great that that mindset exists, but I propose we extend and formalize that a bit. 

Sometimes when issues arise that require a lot of investment in time and energy it becomes really hard to disconnect again. Providing a clear, explicit policy gives us a way to socialize and reinforce the idea that taking time to recharge _is_ an important step in continuing to deliver **quality worthy of art**. It gives managers tools to reach for to provide concrete recommendations. It provides transparency to the org so that we can take rest time into account for when we're planning product deliverables.

## How is this RFC resolved?

The team agrees, we come up with a set of recommendations, leadership and people ops buy in, and we add them to the PDDE time off recommendations.

**Comment by jonallured** [comment]
I love this idea - I would just be very careful about using the word policy here. Recommendations I love, Policy, I'm not sold on. 😸

**Comment by ashfurrow** [comment]
> When dealing with a sustained push to meet a product deadline (i.e. local discovery) take a week to recoup

Haha, how did you know?! 

I'm a 👍 on this RFC. I agree with @jonallured – this should be a _recommendation_, in line with our principle of [minimum viable process](https://github.com/artsy/README/blob/master/culture/engineering-principles.md#minimal-viable-process). It's already an unwritten recommendation, so let's write it down 🎉

**Comment by mbilokonsky** [comment]
Strong agree.

We need something stronger than "props" for e.g. the folks who worked over the weekend to ship LD. Having an off-the-books policy, perhaps where the team lead is responsible for just telling people to take time off when appropriate, would help to offset that, kind of?

**Comment by anandaroop** [comment]
Thanks for writing this up @zephraph, this is a very important thing to surface. And honestly, I think your back-of-the-napkin suggestions above all sound pretty reasonable.

As for policy vs recommendation — having a soft touch here might be fine, but that just makes it all the more important that there actually are some visible + realistic examples of what reasonable time off looks like. 

Otherwise I think we will find some people will not feel entitled to give themselves necessary recovery time. And some will be less likely than others, based on seniority and demographics. This is the unfortunate corollary of the no-policy policy (which is of course a kind of policy).

I definitely support making these norms more visible and social rather than just a 1:1 thing between manager/report.

**Comment by sweir27** [comment]
I agree that we should be explicit/write this down!

The truth is, occasionally these things happen and we should acknowledge them.

The other side is that as an org I _hope_ we're doing as much as we possibly can to avoid these situations (i.e. we should aim to never have sustained/stressful pushes or systems that result in overnight incidents).

So, perhaps in the proposal that reaches leadership/people ops we should be explicit on this point. When we notice these situations occurring, we should commit to addressing the root cause.

But! As we know, sh** happens so explicitly recommending recharge time is 👍 .

**Comment by zephraph** [comment]
Thanks @jonallured, @ashfurrow, @mbilokonsky, and @sweir27 for your feedback. I didn't even realize I'd written the word policy, but I think it's important to address.

@anandaroop, your feedback hits home. 

> Otherwise I think we will find some people will not feel entitled to give themselves necessary recovery time.

I think this is important context. I'm guilty of this. Being stressed or tired sometimes pushes you to make decisions that aren't necessarily in your best interest. Sometimes you're just driven to finish this next thing. And the thing after that. You've been working hard for a while, but just a few more days and a few more things and... before you know it you're in an unhealthy place that you never intended to be in (and wasn't required for you to be). I've been there. That's why being explicit is important to me.

With that framing the context, there's two things here. _Policy_ and _recommendations_. I believe we should have a policy (accepted and supported by the business) that we allow for (and actively encourage) rest and recovery. The policy is to support and encourage but _not_ to require or mandate. The policy is important though because it makes the support of the business explicit. What time should be taken and when should be firmly a recommendation. Still, I think we should have a concrete list of recommendations. It would be an extension to our time off playbook (which is technically company policy). 

Having a playbook doesn't mean you have to make a specific play. But when the game is tight and things get hectic it gives you a well known, well rehearsed course of action to fall back on. I just want us to make it easy to do the healthy thing.

**Comment by SamRozen** [comment]
Artsy's existing policy regarding time off is pretty explicit about supporting people wellbeing (https://sites.google.com/a/artsymail.com/intranet/people-operations/cultural-policies/time-off) 
> Taking time off of work supports your health and happiness, and your health and happiness enable Artsy to achieve its goals, mission, and vision. As such, we empower Artsy employees to take time off based on the desires and needs that matter most to them.
And I have no doubt that the business overall (including leadership, people ops, etc.) is already very supportive of people taking some time off to rest after very intense periods. We don't need to get any additional buy in from them. What do you think is missing on the policy front?

On the recommendations side, I fully agree that listing explicit examples of when it is appropriate and encouraged to take time off will enable people to take the time off they need.

**Comment by zephraph** [comment]
Thanks for that @SamRozen. Since we already have that point in the policy, really all this is is adding recommendations to the PDDE time off playbook (and socializing those changes). 

Would folks like to pitch in on potential recommendations? I'll start with the examples above:

- After dealing with an overnight on-call incident, take the next possible day off.
- After dealing with a high-stress on-call rotation, add two days to your weekend.
- When dealing with a sustained push to meet a product deadline (i.e. local discovery) take a week to recoup

Should we tweak those? What else should we cover?

**Comment by ashfurrow** [comment]
Extending the existing Artsy docs with engineering-specific scenarios makes sense 👍

**Comment by anandaroop** [comment]
Agree — having concrete examples (even if they are just suggestive) will be beneficial to all, I think. In fact, having this discussion out in the open was extremely helpful to me just now in planning some post-launch OOO time of my own for next week 😸

**Comment by mbilokonsky** [comment]
One way to get at the spirit of what @zephraph is saying while also recognizing the validity in @SamRozen's point might be to track examples. It could even be anonymous but something like:

* engineers dealt with overnight incident, took next day off
* engineers had a stressful on-call rotation, took 4 day weekend.
* engineers had a sustained crunch for four weeks, took a week off afterwards.

Because to me there's a difference between "We have a policy of allowing time off for any reason" vs "Here is how people who work here have used the time-off policy", you know? And I think that's kind of what @zephraph is trying to get at.

**Comment by dleve123** [comment]
👍on adding some examples of acceptable PTO schedules as guidance, but not rules. For those looking for the PDDE specific PTO playbook, it's here: https://docs.google.com/document/d/1UPkYOoiAAyV4P9qf7WmfunUcaFQIGqsG96LryoBRnQs/edit

**Comment by dleve123** [comment]
👍on adding some examples of acceptable PTO schedules as guidance, but not rules. For those looking for the PDDE specific PTO playbook, it's here: https://docs.google.com/document/d/1UPkYOoiAAyV4P9qf7WmfunUcaFQIGqsG96LryoBRnQs/edit

**Comment by zephraph** [comment]
## Resolution
We've accepted adding recommendations for time off

## Level of Support
2: Positive feedback.

#### Additional Context:
We've generally agreed that these are recommendations and not specific requirements. 

## Next Steps
Add it to the time off playbook
