### ISSUE TITLE
[RFC] Defining PR roles

### ISSUE THREAD

**Issue by mdole** [artsy/README#177]
## Proposal:

Specify responsibilities for PR reviewers/assignees.

I propose that the following guidelines apply to all PRs created in the Artsy org:

### Reviewers
**People assigned to review a PR should ideally review before merge.** It is not required that *all* reviewers complete reviews, but it is recommended. Authors should also do their best to limit the number of reviewers in order to keep PRs moving quickly. 

**Developers who should be notified of the PR but whose review is not required before merge should be cc'd in the PR body instead of assigned to review.**

Reviewers should make a good-faith effort to review within one business day of being assigned, unless the PR's author specifies otherwise in the body of the PR. If a reviewer requires more time for any reason, they should communicate with the author of the PR so that the author can designate a different reviewer if need be.

### Assignees
**PRs should be assigned to a single person.** This helps to keep expectations clear and stops PRs from getting stuck ("oh, I thought the other person was the more important assignee").

**The person assigned to the PR is only responsible for moving the PR forward (merging or re-assigning the PR), and not necessarily for reviewing.** If the author wants the assignee to review, they should also assign them as a reviewer.

It is still the responsibility of the PR's author to get the PR to the point where it is ready to be merged. It is also the author's responsibility to notify the assignee when they believe the PR is ready to be merged, at which point the assignee should make a good-faith effort to merge or request changes within one business day.

Once an assignee has finished reviewing, they can:
- Merge the PR if comfortable doing so and the criteria below are met,
- Re-assign to the original author so that they can merge, or
- Request additional review from other developers

These criteria should be fulfilled before a PR is merged:
- All CI status checks should be green
- Peril/Danger status checks should be green
- At least one review _approval_ should have been submitted

**PRs should not initially self-assigned** (though they may be assigned back to the author by the original assignee). This ensures that there is a final check from a fresh pair of eyes on before the PR is merged. 

## Reasoning

Different engineers have different practices when it comes to PRs. Some ask 3 - 4 people to review, some only 1 person. Some self-assign their PRs, while others assign them to teammates.

This can create a lot of confusion, especially when engineers transition between teams and have to adjust to the styles of their new collaborators. It also slows the pace of progress, as it maybe be unclear who is responsible for making sure a PR is merged as fast as safely possible.

## Exceptions:

Ideally, this would be applied across teams and individual engineers so that everyone has the same expectations for what happens when they create a PR and designate reviewers and assignees. This would require close to 100% agreement on what these roles are and mean, so I'll do my best to make sure that everyone has a chance to voice their opinions or concerns.

The timelines may also change depending on the urgency of the PR. Ideally, authors will note things like "this is a high-priority PR and would ideally be merged within the next few hours" or "this is a low-priority PR and as such could wait until so-and-so gets back from vacation to review, since they're the most familiar with this system." Could be a good case for a peril rule + auto-tagging, actually.

## How is this RFC resolved?

If we're able to agree on guidelines, those guidelines would become part of Artsy's README and would be surfaced to new hires. They would also be raised in Engineering standups and in the `#dev` channel to ensure that the whole team is aware and onboard.

**Comment by jonallured** [comment]
Awesome write up! A couple thoughts:

First, I think the assignee should be able to merge even if all the reviewers haven't chimed in. My experience has been that some reviewers struggle to get feedback in time and some never do!

Second, implicit in the proposal is an assumption that there is only one person assigned to a PR - might be worth calling that out? I've seen some PRs with multiple assignees so this might be a change for some! Could also be an opportunity for a Peril warning? Something like:

> Oops, looks like you assigned more than one person the PR, link to docs here.

Overall, I think there's a lot of value in striving for a consistent approach to PRs even if there are sometimes exceptions. Thanks again for raising this! ❤️

**Comment by starsirius** [comment]
Thanks for writing this up! Still need to read through it, but pasting [previous discussion](https://github.com/artsy/potential/issues/153) for reference.

**Comment by joeyAghion** [comment]
Just noting that, however this is resolved, it should be integrated with the existing recommendations around pull requests: https://github.com/artsy/README/blob/master/playbooks/engineer-workflow.md#pull-requests

And here are some personal reactions:

> All people designated to review a PR must...

Clarity around review requests would be helpful. Currently we seem to use them as FYIs while the assignee is "required," so I would _not_ want to require reviewers' responses before merging. However we could agree to use them more strictly (and just @-mention those that need FYIs in the PR bodies instead).

> The person assigned to the PR is responsible...

I agree with most of this. I'd just add that assignees can be _modified_ over the course of changes and reviews. E.g., instead of the assignee _saying_ "feel free to merge once X is complete..." s/he can simply un-assign themselves and assign the contributor or another reviewer it's waiting on.

P.S. I like making the 24-hour expectation explicit even if it's not enforced. I.e., if you need any action before this time period, you need to ask explicitly.

> Major PRs should not be self-assigned...

I'd go further than this. Code review is one of the most fundamental quality tools we have, so I'd recommend assigning others _even_ when changes seem trivial. Occasionally when a merge is needed urgently it's forgiven to self-merge, but that doesn't mean it shouldn't still be reviewed by the assignee [later].

**Comment by mdole** [comment]
(wrong button sorry)

**Comment by orta** [comment]
+1 against forcing all reviewers to leave a review

Everything else looks solid

**Comment by mdole** [comment]
Ok, made some updates to the original. 

Key changes:
- Changed "reviews completed before merge" to be recommended and added some language around cc'ing folks (thanks @jonallured, @alloy, @joeyAghion, and @orta!)
- Added block about assigning to a single person (thanks @jonallured!)
- Added block about the assignee's options after they've reviewed (thanks @joeyAghion!)
- More strongly recommended assigning someone to ALL PRs and not just major ones (thanks @joeyAghion!)

**Comment by mdole** [comment]
Let me know if you have more comments! I'll also solicit other feedback throughout the week in the hopes of getting to something the whole team is happy with

**Comment by oxaudo** [comment]
In my personal experience I sometimes make self assigned small PRs and merge them if it is relatively trivial and I need those changes to be in very fast. But in this case I also assign somebody as reviewer and assume that it's helpful as a sanity check even after the fact.

**Comment by dleve123** [comment]
@mdole super stoked that you opened up an RFC on this topic. I have been thinking about doing the same for a while now, but you beat me too it! I'd love to riff off of the conversation already present and provide a few other recommended changes while this topic is fresh on some peoples' minds.

---


## Punchline (TL;DR)

From an operational perspective, I propose that we:

- Always have 1 `Reviewer`, even if this reviewer is the sole `Assignee`.
  - this will allow us to potentially require that an approving review is submitted before merging PRs to Tier 3 (Critical) systems (see @joeyAghion's open relevant RFC https://github.com/artsy/README/issues/176).
- Enforce a 24 hour window from `first PR review requested` to ` first PR review request submitted` via Peril/relevant automation.
- Reframe `Assignee` field values from the "required reviewer" to the "person who should take the next step for a PR".
  - If a non-assigned reviewer (`Person A`) reviews the PR first and would like some follow-up action from another individual, which may or may not be the PR author, (`Person B`), then `Person A` should be at liberty to re-assign to `Person B`.

## RFC responses / Motivation

> People assigned to review a PR should ideally review before merge. It is not required that all reviewers complete reviews, but it is recommended. Authors should also do their best to limit the number of reviewers in order to keep PRs moving quickly. Developers who should be notified of the PR but whose review is not required before merge should be cc'd in the PR body instead of assigned to review.

In my experience at Artsy, often times one of the PR's requested reviewers provides timely and relevant PR review _before_ the assignee does. While, at one level, the ambiguity of this workflow bothers me, taking a step back, I think often this non-assigned reviewer is usually more excited to review the code and/or perhaps has more context/capacity to review.

This is all to say that while the assignee workflow step might be in attempt to avoid some form of a "bystander" effect / general lack of ownership problem, I _think_ that isn't something to solution around ATM.

> Reviewers should make a good-faith effort to review within 24 hours of being assigned, unless the PR's author specifies otherwise in the body of the PR. If a reviewer requires more time for any reason, they should communicate with the author of the PR so that the author can designate a different reviewer if need be.

I am *extremely* pro setting an expectation for PR review response time. I think setting this value to an aggressive but reasonable value (and one that is enforced) is super high-leverage as it sets an upper bound in a long and blocking step in the software development lifecycle (SDLC). I think resolution of this PR should include a task to enforce this time via Peril/relevant automation (and I will gladly pair with anyone to make this happen).

> I'd go further than this. Code review is one of the most fundamental quality tools we have, so I'd recommend assigning others even when changes seem trivial. Occasionally when a merge is needed urgently it's forgiven to self-merge, but that doesn't mean it shouldn't still be reviewed by the assignee [later].

Strongly agree with @joeyAghion here. In fact, I'd recommend changing this issue's description from "Major PRs should not be self-assigned." to "PRs should not start off as self-assigned". Yes, there are always exceptions to this rule, but that can be included in the exceptions section of this RFC. The "start off" language is to provide clarity that there are some times that the author might be assigned (for example, if they are making changes due to PR feedback)

Acknowledging that this might "stretch" the scope of the @mdole's original RFC, I would like to propose that *always* a PR have a `Reviewer`. Github has a [lot of features](https://help.github.com/en/articles/about-pull-request-reviews) that Artsy could decide to use with regards to Code Review rule setting (i.e. requiring reviews before merging) – so I think moving to a SDLC that is rooted around a GH `Reviewer` would, from a infrastructural perspective, set us up for success and future iteration on our SDLC. Moreover, I think there is a lot of value in the clarity provided by `Approved` and `Changes Requested` statuses on the GH review object.

**Comment by alloy** [comment]
Oh yes, I would love for there to be a shared understanding that we use the “Changes Requested” feature of GH reviews when you want really do want changes to be made.

**Comment by mbilokonsky** [comment]
Between email and Jasper I've got a number of filters set up to try to make sure I see the notifications I need to see and don't see the others, but it's still not always 100%. I broadly agree with everything in this RFC, the only thing I'd maybe want to add is some standardization around notifications?

Could we have peril send a slack message whenever we get assigned to a PR? Or if it's our PR, whenever someone submits a review? I find that the feedback loop via slack tends to be a lot tighter than checking for notifications across other apps.

**Comment by ashfurrow** [comment]
I'm a 👍 @mdole The feedback applied to the RFC looks good, one thing I'd change, though, is this:

> should be cc'd in the PR body instead of assigned to review

This is a pretty big departure from some of our workflows, could we highlight this somehow by moving it into its own paragraph or making it **bold** or something? 

---

@mbilokonsky We used to have a "no slacking on PRs" slack bot that would DM you if you were assigned to an open PR after so long, might be useful to bring back.

**Comment by jonallured** [comment]
Note: if we're going to do any sort of Slack integration, I'd hope that it would be opt-in or at least a way to opt-out. I'm not a fan of that workflow and have something that works for me. Getting Slack messages about PR lifecycle events would be noisy for me.

**Comment by dblandin** [comment]
> Reviewers should make a good-faith effort to review within 24 hours of being assigned

How do you feel about rephrasing this to "within one business day" of being assigned to account for pull requests opened on Friday? I assume that we would expect an assignee to review by Monday in that case and not by Saturday.

> Major PRs should not be self-assigned...

I wonder if we can further tease this apart. Maybe if we agreed to avoid review requests for FYIs (and instead encourage CCing in the PR description), we could further lean into review requests to signal "I'd like you to review this diff" and assigning or self-assigning simply shifts the power to merge.

I think this also gets at a discussion of what makes a pull request ready to merge? Some potential guidelines:

- All CI status checks should be green
- Peril/Danger status checks should be green
- At least one review approval submitted

The role of the assignee might then become:

The PR assignee is responsible for merging this PR once the ReadyToMerge:tm: guidelines are satisfied.

If no assignee is specified, I think that should mean the author is on the hook to merge.

One question I have with that approach is if the author would have to request a review and assign the same person to signal 1. Please review this diff and 2. Please merge if all is :heavy_check_mark:.

**Comment by mdole** [comment]
@dblandin @dleve123 thanks for the thoughtful feedback! I agree with much of what you've laid out—here are the updates I propose making to this RFC before resolution:

1. Change language around time guidelines to "one business day" (Devon)
2. Update assignment section to specify that:
  - PR is ready to merge when CI is green, Peril/Danger is green, and 1+ reviews have been submitted (Devon)
  - PRs should not initially be self-assigned (Daniel)
  - If the same person is both asked to review and assigned, they should review thoroughly and then move the PR forward by requesting changes/merging/re-assigning, as discussed elsewhere in that section (Devon)
  - Clearly split out the responsibilities of assignees and reviewers - reviewers review, assignees move the PR forward and need only review if they are also specified as reviewers (Daniel + Devon)

If this sounds good to you, I'll make these updates tomorrow and get this RFC on the road to resolution.

**Comment by mdole** [comment]
## Resolution
We have resolved to adopt this RFC.

## Level of Support
2: Positive feedback. There were suggestions for improvement, but no one raised objections to the content of the proposal.

#### Additional Context:
Responses were pretty favorable across the board. Some things that could become follow-up RFCs:
- @mbilokonsky's suggestion to add Peril/Slack messages notifying assignees when assigned, and/or notifying authors when someone has submitted a review

## Next Steps
I will submit a PR to the README documentation, both covering this change in a document and adding it to the required reading for new team members. That PR will also include an update to the [Engineering workflow](https://github.com/artsy/README/blob/master/playbooks/engineer-workflow.md#pull-requests) documentation on PRs, since this RFC impacts that document.

Once that PR is merged, I will share the final document in the #dev channel.

I will also implement Peril rules (going to shoot for this week) for the following:
- Ping reviewers if they have not submitted a review after one business day of being requested - @dleve123 thank you for the suggestion!
- Notify an author if they assign more than one developer to a PR (thanks @jonallured!)

#### Exceptions
None that I can think of!
