### ISSUE TITLE
Create a doc which states what shouldn't be Open

### ISSUE THREAD

**Issue by orta** [artsy/README#2]
If OSS by Default means starting with open, what are the right arguments for saying something should be closed/private.

Re: https://github.com/artsy/potential/issues/166#issuecomment-412677219

**Comment by joeyAghion** [comment]
Since I brought this question up in another forum, here are a few proposals:

Always private:
* contact or role details for individuals
* any information about candidates or new hires before they've consented to announce they're move (this would include onboarding issues)
* production data or logs (including indirectly through migration output, etc.)
* repositories representing substantial business value, novelty, or criticality (such as the main API, content management system, or auction operator tools)

Maybe should be private, depending on sensitivity:
* security or compliance topics, including pending security work items or GDPR procedures
* incident/support instructions, including data recovery or incident-mitigation procedures
* sensitive business rules, definitions, or implementations (tiering, targeting, buyer/bidder qualification, spam heuristics, search ranking algorithms, data partnerships...)
* un-announced feature work
* industry or user research or analysis that may hold some competitive value
* references to private content (according to the criteria above) including documentation of private systems, links to private gists that may include private data or logs, etc.

The "maybe" category is pretty large and nebulous. Any more concrete criteria we can introduce there could be helpful. Especially valuable would be ways to _enforce_ these considerations over commits or discussions, since lots of content that is already public overlaps with these potentially-sensitive topics.

**Comment by starsirius** [comment]
I'm struggling with the same single-source-of-truth vs. open by default, and want to provide one example recently while working on an onboarding session for new hires.

The [tour of collector experience](https://github.com/artsy/README/blob/345c6c0a376b9854e306ca53e8da7ec96e3ff355/onboarding/sessions/tour-of-collector-ux.md) is a great session to show case Artsy experience as a collector for new hires and is perfect to be public. However, when working on the counterpart, tour of Artsy partner experience, I realized it may not be a good candidate to be public. it includes many internal processes and admin workflow. It's not ideal I have to put our onboarding sessions in different places.

**Comment by orta** [comment]
Yeah, I agree with all of the always and maybes there @joeyAghion 

I don't think there is a one-size fits answer all unless we move all documentation private, and personally I'd rather that didn't happen - when we had them private . Yet, if folks feel strongly about it though, we can have an RFC for it though!

We have contemporary examples in the [platform practice docs](https://github.com/artsy/README/blob/master/practices/platform.md) in README where it jumps from  README to Potential pretty seamlessly because most of the useful platform docs need to be private.  Maybe the answer is to move both to potential and just say that's where they live if they need to be I the same place? We don't need to be dogmatic about it.

**Comment by erikdstock** [comment]
Closing this issue as stale
