### ISSUE TITLE
[RFC] Package for triggering when element enters viewport

### ISSUE THREAD

**Issue by ansor4** [artsy/README#236]
### New Dependency

Name: `react-intersection-observer` ~~or `react-visibility-sensor`~~

URL: https://www.npmjs.com/package/react-intersection-observer ~~and https://www.npmjs.com/package/react-visibility-sensor.~~

EDIT: After digging into both libraries, I propose we only consider `react-intersection-observer`. While both libraries are actively maintained and in use, `react-intersection-observer` is written in Typescript (which integrates nicely with Artsy's preferred stack) and includes a component with similar functionality to the `VisibilitySensor` in `react-visibility-sensor`.

### Focus

Allows us to track impressions of components when they enter viewport. Could be used in the future for triggering other actions when components enter viewport

### Check List

- [x] Have read over the source code
- [x] Has had a release in the last year, or looks done and stable
- [x] Could you fit this codebase in your head after reading the source?
- [x] Is this the stand-out obvious answer to a particular domain problem?
- [x] Do you expect your team to be the only people who know about this dependency?
- [x] Is this obviously being used in production by the maintainers, and thus battle-tested?
- [x] Do you feel well versed in the domain of this dependency and/or could maintain it if that needs to become an
      option?

### Alternatives

Roll our own implementation with intersection observers.

**Comment by ashfurrow** [comment]
Sounds good to me. Seems like the exact kind of non-core functionality that we should rely on OSS for 👍 

From the readmes, `react-intersection-observer` seems like it a nice, comprehensive API (importantly, it exposes a React hook).

**Comment by zephraph** [comment]
I'd second using `react-intersection-observer` for two reasons:

1. Overall it looks like a well structured, well maintained library. It's small, the project is written in typescript, and it has plenty of comments. I feel like this is something I could contribute to if I ran into a bug, which is a huge plus
2. Intersection observers are generally useful for other problems and gives the overall library more utility

Generally, I don't feel like this problem is something we need to fully implement ourselves.

**Comment by ansor4** [comment]
Agreed! Just looked over the source code, and it looks like `react-intersection-observer` includes a `InView` component that basically serves the same functionality as the `VisibilitySensor` component that `react-visibility-sensor` includes. That plus typescript are more than enough to only consider `react-intersection-observer`.

**Comment by zephraph** [comment]
cc @damassi are there any dependencies that you can think of that cross over functionality on this? 

Being that this is somewhat of an analytics use-case is react tracking already doing this sort of thing? I'd be a little surprised if we weren't doing this somewhere else.

**Comment by damassi** [comment]
Nope, react-tracking doesn't do viewport detection. I _think_ I may have seen something similar with `react-waypoint`, in article pages. @eessex, thoughts?

**Comment by eessex** [comment]
We use `react-waypoints` widely for this in publishing and it is already in a number of repos including Reaction and Force.

**Comment by ansor4** [comment]
Hmm, this does seem to overlap quite a bit with `react-waypoints` in terms of the problem both packages try to solve, so it's worth discussing whether we should consider `react-intersection-observer` at all.

If given a choice between the two, I'd probably advocate for adding `react-intersection-observer`. The simplicity of the library is appealing, as well as the Typescript aspect of it. It seems like using the Intersection Observer API is the path forward for this type of functionality (`react-waypoints`, for example, has an open issue to re-implement using IntersectionObserver).

At the core, I _think_  the difference is that `react-waypoints` uses `Element.getBoundingClientRect()` to check if an element is in the viewport. This call runs on the main thread, so they build up and cause performance issues. `react-waypoint` also calculates visibility based on scroll position of an element in a scrollable container. This presents a limit that the devs recognize: we can only use a waypoint component in at most one scrollable container. I take this to mean that we wouldn't be able to use it within carousels for example.

Using IntersectionObserver lets you register a callback that is executed whenever an element enters/exits a viewport or element, so it frees the main thread and is more performant. The one thing Intersection Observer API can't tell you: the exact number of pixels that overlap or specifically which ones they are. However it covers the case of "If they intersect by somewhere around N%, do something"

**Comment by zephraph** [comment]
Ahhh, yes. Very fun. 

Monitoring visibility via scrolling is a classic problem with unfortunate performance impacts. That's the whole reason intersection observer was proposed by browser vendors. From that perspective, @ansor4 I agree with you.

We should note that because intersection observers are a newer [browser feature compatibility](https://caniuse.com/#feat=intersectionobserver) will need to be considered. Globally it has 88% support, but that does _not_ include any IE coverage (even 11). 

Certainly my preferred approach would to be to rely on intersection observers and either fallback to scroll monitoring or polyfill intersection observers to achieve the same effect. That's what the lazy loading library we use does. 

Whatever our choice, we should do our best effort to consolidate and simplify. That work doesn't need to be done immediately, but we should at least note it somewhere.

**Comment by damassi** [comment]
Note that the only IE browsers we support are Edge+

**Comment by ansor4** [comment]
We seem to have quorum here and we've already successfully introduced this package in Volt, so I'm going to go ahead and close this RFC.
