### ISSUE TITLE
[RFC] Create a technical plan before starting work on projects

### ISSUE THREAD

**Issue by zephraph** [artsy/README#245]
## Proposal:

Before beginning work on a project, we should have a dedicated technical plan. This isn't to say that we aren't already doing planning, but rather an effort to make our planning more consistent, deliberate, and discoverable. 

At a high level the plan could include:

- Motivation (why are we doing the work?)
- Impact (who or what is impacted by the work?)
- Approaches (how will we do the work?)
- Risks (what should we watch out for?)
- Decisions (what do we need to decide on to progress?)
- Outcome (what does success look like?)

Technical project plans _should_ be stored in a similar location that make it easy to find from team to team. My recommendation is in notion under [Product] > [<team>] > [Technical Plan]. 

## Reasoning

- Assumptions may form that a certain part of a project was thought out or discussed but it may not actually have been. Writing it down makes it explicit.
- Placing project plans in a consistent, searchable space makes it easier for people to discover historical decisions and keep in tune with on-going work
- It'll force us to cover our bases

## Exceptions:

If a single ticket is sufficient, you probably don't need a plan. If the work takes more than a sprint, you definitely _do_ need one. Keeping with our principle of [minimal viable process](https://github.com/artsy/README/blob/master/culture/engineering-principles.md#minimal-viable-process) we only want to do a thing when it adds value. Use your best judgement. 

## Additional Context:

Here's the [slides](https://docs.google.com/presentation/d/1EpvkcmabLy-bok9WRsq3ArBYJcsjYau0f_Ul5G_h06Q/edit?usp=sharing) from our mini-conf on this topic

## How is this RFC resolved?

We agree to start creating technical plans and storing them in a particular place. 

---

If you have ideas of how to improve this proposal, please let me know!

**Comment by ashkan18** [comment]
awesome!  Im thinking how can we make the project part of 👇 broader
> Before beginning work on a project
I think anytime someone wants to make decision between few possible solutions/options or they are building things that impact other teams and maybe other cases they should consider technical plan. 
I've personally used this in the past to make decisions with others helps and get their opinion on things that could technically be considered smaller than a project.

**Comment by sweir27** [comment]
This is great! I'm excited to formalize this/get started.

One minor note-- an initial step after this RFC is resolved could be to co-locate the existing technical plans as a way to seed the effort, + create a template that can be easily extended.

**Comment by dleve123** [comment]
A couple of thoughts. I'd encourage us to: 

- consider **multiple** approaches as part of the technical planning process, but then choose one at any given time. I think demonstrating in a technical plan that multiple approaches were considered, and one was deliberately decided, shows the planning process was robust, and didn't have a single approach in mind at the onset of planning. Moreover, I think explaining why one opted to _not_ go with a certain approach is really educational as well.

- embrace the mindset that it's **okay for plans to change given further information**, we shouldn't feel constrained, but supported by a technical plan at any given time.

---

In terms of stance on this RFC, I'm +1 on _encouraging_ a technical planning process such as the one in this RFC, but -1 on enforcing / standardizing one quite yet. I don't think enforcing / standardizing was suggested, but just wanted to be extra clear!

**Comment by zephraph** [comment]
@dleve123 I updated the wording a little bit to be clearer that multiple approaches are encouraged. That was the original intent. 

Indeed, this isn't meant to be a be-all-end all for a project. Plans will change, new work will be discovered, and we'll have to pivot from time to time. This process is more about active ideation and giving teams a framework to build upon to facilitate more explicit planning. 

The intent of this RFC _is_ to facilitate the creation of technical plans in a consistent, discoverable location. The outline given is more of a recommendation and teams can use whatever sections they feel are required given their project scope. However, it would be good to get teams to commit to having _something_. Likely, this isn't anything new (I hope all teams are planning and writing things down) it's just adjusting where we store it.

**Comment by mbilokonsky** [comment]
I kinda like the idea of resolving this RFC by creating a template in notion, and that a part of that template asks us to write down other approaches we considered and the reasons why we chose not to pursue them. Obviously that won't be exhaustive, but can often help bring a new team member up to speed on a project by documenting the assumptions and reasoning that went into the technical decisions they're inheriting?

**Comment by joeyAghion** [comment]
1. I'm very in favor of having a lightweight template like this to encourage engineering choices to be spelled out, even if reasonable or non-controversial.

2. We discussed elsewhere how getting feedback from _outside_ a team can also be critical to ensuring new technical work is aligned with [and not duplicative of] existing patterns and solutions. I think this document can be a good and open way of soliciting that input from relevant experts across engineering. Might be worth calling that out.

3. When appropriate (e.g., when considering significant new systems, technologies or architectures), a face-to-face design review can efficiently drive consensus about these plans. We've used a very similar template in advance of those, so I suggest just consolidating them. Those technical review docs have included these additional prompts:
* existing technology (important to consider what systems may relate to the new work and need migration or retirement)
* proposals (this is maybe a more inviting way to introduce "approaches" 🤷‍♂)
* questions (I like explicitly listing these out, and they feed nicely into "decisions")

4. +1 to @dleve123's suggestion of explicitly prompting for "alternatives" that were considered.

5. I might put "decisions" last, since that neatly allows significant _changes_ of direction to be appended to the doc for posterity.

**Comment by izakp** [comment]
+1 to @joeyAghion 's suggestion of having a lightweight template approach

**Comment by mbilokonsky** [comment]
A quote I've always loved is Bruce Lee's line: "Coming to conclusions is the opposite of learning."

I like the way that this RFC seems to be converging on optimizing for learning, rather than making decisions - it's almost like the real value add here is at least half driven by having a place where we can solicit and log feedback from stakeholders across related domains. Maybe even shifting the focus of this conversation to explicitly make that the priority could help shake out a few other implications?

**Comment by dleve123** [comment]
I am curious (and this was something that was brought up in standup this past Monday) about  what is the expected lifetime of RFCs? I personally have a distaste for things that linger in unresolved states, but also think it's not great for organizational health.

Seems like there's pretty clear consensus that this is a positive addition to our engineering culture, so can we close :) ?

**Comment by zephraph** [comment]
It's on my todo list to resolve this today, but thanks for the reminder. 

I've just got to copy over the resolution statement and get everything together. Soon.

**Comment by zephraph** [comment]
## Resolution

This RFC is accepted with some teams already implementing technical plans. More details around specific organization of plans TBD. 

## Level of Support
2: Positive feedback.


#### Additional Context:

There were concerns about how formalized this process was and whether or not it constitutes a standard. We'll put our best foot forward and try for consistence where feasible while holding to our principle of [MVP](https://github.com/artsy/README/blob/master/culture/engineering-principles.md#minimal-viable-process)

## Next Steps

- Organize technical plans in a structured way

#### Exceptions

It's up to your team's best judgement if you need to do a technical plan or not. They are strongly encouraged for anything other than trivial changes, but that decision ultimately lies with the team.
