### ISSUE TITLE
RFC: Cloud provider ethics and values

### ISSUE THREAD

**Issue by izakp** [artsy/README#300]
## Proposal:

We hold our cloud provider to our same values.  After reading about Amazon's [reaction to Coronavirus encouraging employees to trade sick days](https://www.commondreams.org/news/2020/03/13/grotesque-level-greed-owned-worlds-richest-man-jeff-bezos-whole-foods-wants-workers) I think we should realign to a new cloud provider once we get onto Kubernetes and have the tooling necessary to do all of our Postgres migrations.

## Reasoning

We want to have secure, reliable cloud infrastructure at a reasonable cost.  But we also should consider our providers align with our values and goals.

## Exceptions:

I previously brought looking into green hosting via https://www.thegreenwebfoundation.org/ - AWS claims to be tackling sustainability but it's not the entire facet we should evaluate our cloud provider or datacenter on.  We should consider sustainability as well as good labor practices.

## Additional Context:

https://artsy.slack.com/archives/C03J4L2KK/p1584192238002500

## How is this RFC resolved?

I would like to converge on a provider we are happy with that could satisfy our needs while upholding our values. then we can plan a roadmap for platform infrastructure / migration accordingly.

**Comment by zephraph** [comment]
This is a hard thing to respond to, but I really want to add my voice to the conversation. I feel very vulnerable replying to this, so please understand that I just want to help the team have a healthy conversation around this topic. 

Let me start by saying I in no way agree with how Whole Foods/Amazon handled this situation. I think it's important that companies take care of their workers and folks shouldn't have to be worried if they will be able to take time off if they get sick during a pandemic. 

That said, I don't agree with moving cloud providers with that alone as a justification. I firmly don't believe Google is any more moral of a company. Microsoft has been building their good will with devs but largely everyone would've said they were toxic 10 years ago. 

I have to imagine that any cloud provider move is going to have a _significant_ cost to Artsy. Even after we're fully migrated to kubernetes, we're always going to have to learn more about the underlying services. That knowledge transfer has to happen across the _entire_ team. We'll always have to deal with abstractions of the cloud provider. We _can't_ escape that. 

I'm not saying we shouldn't use our principles as a factor when picking technologies. Let's definitely do so. That's part of what makes Artsy so special. But we have to balance that with the needs and cost to Artsy. Our mission is to help expand the art market to support more artists and art in the world. If we succeed more artists can devote their life to doing what they love as their full time gig. And because we care and have such strong principles we can continue to use our voice to help shape this company into something that people can look to as a model of what it means the be a business that adds values to people's lives.

If we consider moving cloud providers, I'd want to see how it helps us get closer to our goals. Will in be cheaper? Will it be easier for our developers to use? More stable? Can we do it in a reasonable amount of time with a limited investment? 

I just don't want us to be in a position that we spend a lot of time migrating and the company associated to our new cloud provider does some unethical thing in the name of capitalism and we're back to this conversation. I hope saying that doesn't make me sound like I'm apathetic or a bad person. I _do_ care. I just don't think moving cloud providers will do any thing to help us fix a broken system or in any way absolve us from participating in it.

**Comment by ashfurrow** [comment]
I agree with Justin. I don't think we'll find a totally-ethical cloud provider. This kind of move would be _really_ costly to Artsy in the short-term, and would not really help apply pressure on ~Amazon~ Whole Foods to change their behaviour.

That's not to say we shouldn't oppose those behaviours – I just think that we should oppose them as human beings and citizens, rather than as consumers.

**Comment by izakp** [comment]
I hear your concerns @zephraph and @ashfurrow - it would incur significant engineering cost particularly for platform team but I would point out that there is likely a cost benefit for us as well if we don't stay locked into one single provider.  Perhaps I should clarify I opened this proposal in order to plan our roadmap for the medium to long-term future and am not advocating for taking on a huge amount of short-term risk or work... we will in any case incur costs upgrading Kubernetes and performing other maintenance tasks anyway.  There could be other benefits for us as well if we are more flexible.  See cost comparisons for Kubernetes hosting last year https://www.presslabs.com/blog/kubernetes-cloud-providers-2019/

**Comment by izakp** [comment]
In terms of ease to use, I don't think it matters for developers who are interacting with Kubernetes via Hokusai / the k8s Dashboard.  What we could save on is the Kubernetes provisioning tooling via kops and instead adopt a fully-hosted solution.

Additionally, we would need to research stability and features offered by each Kubernetes provider, so it's possible GKE offers better overall stability and ease of maintenance as well as cost.

That said, I don't think there is a 100% ethical cloud provider and I agree that there will be no perfect solution here.  (I don't think there is in reality any sense of perfectly ethical consumption.)  But I wouldn't want that fact to restrict our decisions.

**Comment by izakp** [comment]
P.S. following up with looking at all facets like cost and reliability as well, take a look at Digital Ocean's pricing in the above comparison - almost half of either EKS or GKE.  This could save us significant cost we could then reinvest in other ares, including but not limited to further engineering hires #PeopleAreParamount

**Comment by joeyAghion** [comment]
Choosing cloud services isn't that different from other [technology choices](https://github.com/artsy/README/blob/master/playbooks/technology-choices.md). There are a _lot_ of considerations like features, community, compatibility, support, cost, and engineering time (the big one). One could ask similar questions about any of our other choices.

If we attempted that, though, I doubt that _any_ of our technology choices would stand up to the scrutiny. Could we use design patterns documented by a bigot? Contribute to an open-source library authored by a chauvinist? Subscribe to a service partially owned by a Private Equity firm that has mistreated employees? It's overwhelming [and I think impossible] to navigate it all. Even more so as events evolve, or leadership/ownership change, or our team's preferences change. Instead, I suggest a set of principles like:
* Assume that _no one_ and certainly _no organization_ would stand up to comprehensive ethical scrutiny.
* Assume that we have something to potentially learn or adopt from _everyone_ anyway.
* Strive to make choices according to [our framework](https://github.com/artsy/README/blob/master/playbooks/technology-choices.md) and the best interests of the company and team.
* Where applicable, continue to improve that framework. E.g., some ethical or macroeconomic concerns might truly present some product or reputation risk and warrant careful evaluation.

The primary reason we're all assembled in this organization is to have a positive impact on the world through the company's goals. If we do that well, I'd hope the psychic and financial rewards lead to _lots_ of further opportunities to contribute to meaningful causes in individual, discretionary ways.

**Comment by anandaroop** [comment]
Thanks Isac for bringing up this difficult and important topic.

I honestly don't have a  prescriptive answer to this, but just want to be in dialogue with some of the points raised so far:

- I agree that corporate reputations are labile things, that change over the years in response to their most visible actions. Bezos/Amazon's reputation may be deservedly lousy right now, but I wouldn't put stock in any other tech behemoth standing the test of time.

- I also agree that no corporation, perhaps not even ours, would survive a high level of scrutiny into all of its practices, or board membership, or funders. But I don't think that entirely absolves us from considering any particular company's behavior before giving them our money — or taking money from them, or being associated with them. Consider that when we found out our banner ads were appearing on certain disreputable websites after the 2016 US elections that [we acted](https://artsy.slack.com/archives/C02531TUD/p1480701037000748) to put a stop to that quickly. Certainly there is some threshold for misconduct or misanthropy that compels action on our part. I think it is at least reasonable to ask if Amazon meets it.

- The question of what it costs us — in friction, lost productivity, engineering time — is a complicated one and I don't have any special insight into what would be a reasonable cost to bear, especially under the present outlandish world conditions. But I would expect the cost to be non-zero and that we would need to collectively embrace that as an organization, simply because any meaningful solidarity would be expected to have such a cost.

- And I guess this that leads to my final thought. In order for this to actually *be* an act solidarity I think it would need to be part of a campaign, one  that somehow connects to the affected workers (at [their](https://www.coworker.org/petitions/global-retail-worker-sick-out) [stores](http://www.nottinghammd.com/2020/03/25/attorneys-general-call-on-amazon-whole-foods-to-provide-paid-leave-to-employees-during-covid-19-pandemic/), at [their](https://www.vox.com/recode/2020/3/19/21186322/amazon-warehouse-coronavirus-covid-19-worker-tested-positive-delivery-station-queens-new-york)  [warehouses](https://www.businessinsider.com/amazon-workers-strike-coronavirus-2020-3)). Otherwise it remains an isolated act of consumer activism, whose shortcomings you've already acknowledged above.

Anyhoo... to bring this back down to earth. Is there some small thing we could to (on whatever timeline we'd deem sensible at this moment) to even validate the portability of our infrastructure? What's an incremental step that you could envision?

Whatever the outcome of this, I commend you for raising it.

**Comment by izakp** [comment]
Thanks for the comments everyone - I think @anandaroop you make a salient point, and will take this away as the outcome, to _ validate the portability of our infrastructure_
