### ISSUE TITLE
[RFC] Drop setup scripts and replace with docs

### ISSUE THREAD

**Issue by izakp** [artsy/README#336]
## Proposal:

Drop setup scripts in Potential, Gravity and other repos and replace them with playbooks specifying which dependencies need to be installed.

## Reasoning

While setup scripts for onboarding new developers like  [in Potential](https://github.com/artsy/potential/blob/master/scripts/setup) or [getting set up with Gravity](https://github.com/artsy/gravity/blob/master/script/setup) are intended to  be convenient, in practice they  often prove a hinderance to getting a development environment set up, due to differences in platform  (Darwin / Linux) package managers (apt / brew)  or changing dependencies in Homebrew cask / mainline versions of software like Java and Elasticsearch.

This RFC aims to drop these scripts completely, and instead simply  specify which dependencies are required for a given project and let the developer install and configure them by their own methods.

## Exceptions:

I  don't see any exceptions - I  think this is an example of overengineering and adopting this would mean we trust our developers to be proficient enough to configure their own workstations.

## Additional Context:

See problems recently with Homebrew and Java distributions https://github.com/artsy/potential/pull/353

## How is this RFC resolved?

Some guidelines or best practices - a playbook around dependency management.

**Comment by jonallured** [comment]
I'm on board! My approach to setup is reflected here:

https://github.com/artsy/impulse/blob/7c3a158263ef73566ea1a8a8b9b13e6c39c2d896/bin/setup

This setup script is specific to Impulse and rather than trying to install things for you, merely checks for what the project will need and alerts the developer about how they may want to install it. It's not perfect mind you, but I believe it's on the right track. That part about setting up an `upstream` remote sorta seems stale, but I digress...

My preference is for setup scripts to be defined on each project and to fail with good errors when things aren't installed that the project depends on, but not to take that extra step of installing them for me.

**Comment by pepopowitz** [comment]
I like the setup scripts -- for me they've worked the majority of the time, and when they haven't, they still provided me guidance on what I needed to do to complete the setup. The most time I ever spent on a setup script was when I first started, and I didn't know anything about ruby or ruby version managers. I needed a lot of help to get past those steps, but I would have needed help whether I tried to run a script or follow docs. 

I'm also afraid that using docs instead of scripts would result in more time spent helping people figure out which dependency they missed while setting things up themselves.

**Comment by damassi** [comment]
+1 to @jonallured's impulse script! I actually haven't seen that approach before and it makes an enormous amount of sense; most, if not all, setup scripts on artsy repos have failed me in one way or another for any number of reasons.

**Comment by ashfurrow** [comment]
I'm a big fan of setup scripts, even if Eigen doesn't take full advantage of them 🙈 When I've needed to work in other projects, like Pulse or Gravity, having a script helps me get productive quickly. Even if they fail, I know where they fail and can get that step done manually, and then re-run. 

I would be in favour of adopting Jon's approach to scripts, to be more developer-friendly, but I wouldn't want to throw away the value of setup scripts because of one problem installing one dependency.

**Comment by izakp** [comment]
> I like the setup scripts -- for me they've worked the majority of the time, and when they haven't, they still provided me guidance on what I needed to do to complete the setup. The most time I ever spent on a setup script was when I first started, and I didn't know anything about ruby or ruby version managers. I needed a lot of help to get past those steps, but I would have needed help whether I tried to run a script or follow docs.

I sort of agree with this - I have encountered the situation where a setup script doesn't work but it does provide me guidance on what I should do - that said I get into the position running a setup script that it fails halfway through, I change the failed command and install a dependency some other way, then copy-paste the rest of the script into the terminal. At this point I am doing things manually so would have just preferred a doc so give up on running the script.  That's sort of the motivation behind this RFC.

At this point I see running these scripts as a bad idea because it may try and configure something I don't want, i.e. the project may use `rbenv` while I use `rvm` or it may try to install a `cask` version of Java while I have it already installed some other way from some other project, or install a `brew` version of Postgres where I may have installed it some other way.

I think my problem with these scripts is that they all assume you are starting from a clean slate?

**Comment by izakp** [comment]
> I'm also afraid that using docs instead of scripts would result in more time spent helping people figure out which dependency they missed while setting things up themselves.

I think this time well spent though.  Perhaps an approach to scripts like @jonallured 's script above makes it more pedagogical, which is what I am trying to get at here - more instructive, less automation.

**Comment by izakp** [comment]
Here's an example of what I see as this anti-pattern in Gravity's setup scripts https://github.com/artsy/gravity/blame/master/script/setup#L16

```
svn export https://github.com/artsy/docker-images/trunk/elasticsearch/5.6/artsy-similarity-plugin-1.0 /usr/local/Cellar/elasticsearch\@5.6/5.6.16/libexec/plugins/artsy-similarity-plugin-1.0 --force
```

This script assumes you have `svn` installed and newer versions of Xcode don't - ran into this with @alexpopa-artsy the other day.  Additionally it assumes you want to install our custom similarity plugin to a brew-installed elasticsearch.  

What we need to do is download the jar `https://github.com/artsy/docker-images/raw/master/elasticsearch/5.6/artsy-similarity-plugin-1.0/artsy-similarity-plugin-1.0.jar` and place it in your local elasticsearch's `./plugins` directory.  But I think this script obfuscates what we actually need to do here and we would be better off just documenting this.

**Comment by pvinis** [comment]
Totally. for this one for example we could document that this jar is needed, with an example of how to get it using svn and the next dev that does it with wget can add this as an example as well. but the main thing is you need that jar, so if someone is confident they know how to get it, great. if not, they can look at the examples for instructions/inspiration.

**Comment by joeyAghion** [comment]
I disagree that docs will tend to be more accurate or reliably updated than a script. If you compare our own org's docs to its  code, I think you'll find that--while they both need regular maintenance and can fall out-of-date--code is more likely to receive that care.

> Let's assume we are all proficient developers here...

This runs contrary to the principles of safe, fast, high-quality software development. So much of our process (code review, mentorship, incident-handling, style guides, continuous integration...) is designed to converge our work product on the best any of us can produce, rather than assume we'll each produce brilliant work independently, all of the time, in every technical context. Our areas of inexpertise are all different, but we all have them.

We've always tolerated variety in development environments, but we have so many projects and dependencies and stacks that I think it's _critical_ that there be a default and easy way to get any particular project running. The burden to customize should be on those with divergent preferences, not those just trying to get started or get something done. This "default" won't satisfy everyone, but it will allow us to do more diverse and powerful things.

That said, we could make these assumptions more explicit and better support opt-outs. I like the idea in the examples above, of making setup scripts more self-describing. I'd go a step further and recommend that the scripts default to _performing_ the setup steps rather than just describing them (where possible), with the option to skip any particular step. There's a fine line here between making setup scripts more general and dynamic, and doing too much ugly bash-scripting, but I hope we can find a balance of simplicity and flexibility.

Relevant:
* [Runbook](https://medium.com/braintree-product-technology/https-medium-com-braintree-product-technology-runbook-be6f072cfc0d) is an interesting approach to this combination of manual and automatic steps.
* The Google SRE chapter about [Eliminating Toil](https://medium.com/braintree-product-technology/https-medium-com-braintree-product-technology-runbook-be6f072cfc0d) describes the _costs_ and _risks_ of this sort of manual work, even when it's something we might enjoy.

(Re. using `svn` to install the custom Elasticsearch plug-in, I [hated it too](https://artsy.slack.com/archives/C9ZJYFDNF/p1597683617397200?thread_ts=1597683178.395300) but it [appeared to be](https://stackoverflow.com/questions/9609835/git-export-from-github-remote-repository/18324428#18324428) the most concise, already-available method to download a subdirectory from a github repository. That followed repeated confusion from developers trying and failing to run tests, needing to comment out lines in the source, and [at one point](https://github.com/artsy/gravity/pull/12643) mistakenly disabling custom similarity in `master`.)

**Comment by izakp** [comment]
Edited the expected outcome of this RFC to be a playbook or other docs on dependency management, because I don't see a silver bullet here in any approach.

**Comment by erikdstock** [comment]
I'm a :+1: on removing setup scripts wherever possible and standardizing them where it isn't. Due to being setup scripts (& thus how infrequently they are used) they tend to be one of the most brittle parts of an application setup, and are often run by someone who is new to a repository, possibly obscuring helpful context with a more black-boxed script.

I also agree that most language and version manager installations should be specified as prerequisites and entrusted to the owner of the development environment. In general I disagree that a buggy script is good because it makes you learn something.

If some people like them a more happy medium might be to standardize these where we do use them - maybe using Makefiles (unless there is a better general task runner for unix systems), and
- make them as explicit as possible (eg log why a command is running and exactly what it is prior to executing it) - also possible with `--dry-run` on makefiles
- include separate tasks for installing very specific tools as a convenience but not execute them automatically (eg, if `sbt` is not installed, exit with a helpful message telling the user they need sbt, don't install it for them, but maybe there is a task for doing so)
- require they be idempotent & safe to re-run after a failure

**Comment by izakp** [comment]
Closing this - let's try and adopt in projects a more generalized or flexible approach to setup scripts via Makefiles or Runbooks.  Thanks all!
