### ISSUE TITLE
[RFC] Relaunch the Platform practice

### ISSUE THREAD

**Issue by joeyAghion** [artsy/README#86]
## Proposal:

Restructure the Platform practice to embrace getting platform-aligned work done throughout product teams. To achieve this, we should reset the practice's membership and cancel the inconsistent stand-up forum. Instead, self-selected engineers should come together more deliberately in a weekly hour-long session to review (1) active projects, (2) trends around performance, incidents, risks, and (3) an in-depth topic based on an evolving, openly-curated agenda. This is hopefully where opportunities, projects, or decisions can surface.

This would be a significant investment of time for its members, so we should re-evaluate the format and interval after a few iterations. By agreeing on each meeting's in-depth topic in advance, we could also support engineers opting-in to _some_ sessions without committing to all of them.

For reasons like that, we should encourage (but not enforce) that each product team be represented within the practice.

Finally, for clarity we've been talking about renaming the Platform _team_ to _Infrastructure_. It's less ambiguous with the practice that way. It also more directly points to the specific KPIs for which the team can be accountable, as opposed to long-term platform-wide concerns that benefit from more collective ownership.

## Reasoning

The practice hasn't settled on a productive form or forum since the reorganization of product teams. The current practice stand-up is attended inconsistently and doesn't allow us to discuss and resolve anything in-depth. Instead, these discussions happen in ad hoc design sessions, [too late] on pull requests, or not at all.

Important projects like BNMO and local discovery provide clear opportunities to build new capabilities for the entire platform, but in practice we've preferred to do that work in close collaboration with (or _in_) focused product teams. More minor projects also benefit from being executed in ways that leverage platform resources and advance the _whole_ product.

Finally, we have a new, bigger team. The "practice" should be open to everyone rather than an artifact of the original Platform team.

## Exceptions/Risks:

A major challenge will be ensuring platform-wide priorities are adequately recognized and integrated with product work. At the very least, notes, resolutions, outcomes, or documents should be reported out to the rest of engineering. When significant projects need investment, these will have to be either prioritized by the Platform _team_ itself (Infrastructure!), lobbied for in product teams by practice members or technical leads, or escalated to quarterly priorities such that they're staffed explicitly.

## Additional Context:

It's helpful to imagine examples of in-depth topics we might take on as a practice:

* Modeling of offers
* Stack preferences for admin/management utilities
* Monitoring gaps
* Collecting, assessing, and prioritizing opportunities to deprecate systems or features (Torque, delayed_job, consul, Twitter auth, invoicing, inquiry questionnaires...)
* Performance trends
* Results of stitching experimentation
* Staging data persistence and QA-ability
* Iterating on a whole-platform architecture diagram

**Comment by joeyAghion** [comment]
Additionally, the new practice could have clear goals such as:

* Ensuring consistent and additive service design across the company
* A forum for recognizing and acting on technology trends, risks or opportunities
* A service or boost to product teams rather than a hindrance

(Feedback welcome.)

**Comment by pepopowitz** [comment]
👍 for the renaming of Platform to Infrastructure. That's how I'd mapped it in my head already, anyway.

**Comment by bhoggard** [comment]
Does the consolidation of the auction engine into Causality belong on the project map too?

**Comment by ashfurrow** [comment]
This makes sense to me (as a collaborator, but not member, of the Platform team&practice).

> Finally, for clarity we've been talking about renaming the Platform team to Infrastructure. It's less ambiguous with the practice that way.

Big 👍 from me on this idea.

**Comment by zephraph** [comment]
I'm definitely 👍 on this. All of our product teams are making platform/infrastructural level decisions at some level during larger product work. Having a forum to facilitate how we're working makes a lot of sense.

**Comment by cavvia** [comment]
+1 for renaming Platform team to Infrastructure and orienting its goals around more concrete KPIs. By narrowing the scope of the core team, I think this gives the practice a real _raison d'etre_ as a way to come together to discuss best practices around service design, modelling and cross-team performance issues.

**Comment by dleve123** [comment]
Let's consider Hokusai.

Hokusai is a developer interface to a Kubernetes cluster -- it provides easy-to-use abstractions for deployments, accessing developer consoles, managing environment configuration, etc. Creating and managing Kubernetes is most definitely an Infrastructure concern, but, under my understanding of Platform Engineering, _building tooling to easily interact with Kubernetes (aka building hokusai)_ is exactly the type of work a Platform Engineering team performs.

If Artsy wants to, in a first-class manner, continue to develop systems like and patterns supported by hokusai, then I think having a team titled Platform Engineering is fitting and accurate.

I believe Infrastructure might be too limiting. To be concrete, I would presume that an Infrastructure team would manage a Kubernetes cluster, but not necessarily build tooling like hokusai.

--

A theme in the previous comments on this issue is that there's naming collision between the Team and the Practice. As a new member of the Platform Team and I guess Practice, I've found the goal and responsibilities of the Practice to be confusing (as well described by Joey), resulting in a personal feeling of organizational unclarity, which is a bit of a bummer.

--

Given this, I'd propose that we keep the Platform Team named the Platform Team, and reset the Platform Practice to be in a "discovery mode": unencumbered by legacy org design, we can rediscover the human interfaces needed with the rest of the product and engineering teams, and name this thing as we learn more. I'd propose that we delete the practice, wait a couple of weeks, and then reflect on what is and isn't working with across Artsy's service, and the solution from there. This would solve the naming collision, and _simplify_ organizational design by deleting some organizational constructs.

My 2¢ as a new member of the team!

**Comment by joeyAghion** [comment]
I like the idea of emptying and rebuilding the "practice." At least, the google/slack groups and associated calendar events.

Re. the name, I agree that the team does intend to be accountable for more than the operation of certain back-end systems. At a high-level I imagine the KPIs to be around performance, quality/reliability/incidents, and velocity (so, e.g., including concerns of tooling). I wouldn't want the "infrastructure" name to appear to exclude any of those. I did like how it cleared up the ambiguity with the practice though.

_Reaches for thesaurus..._

**Comment by joeyAghion** [comment]
Please keep any feedback coming, but:

## Resolution
Relaunch the practice!

## Level of Support
1: Overwhelming positive feedback 😍

#### Additional Context:
There was broad agreement about the ongoing need for an improved cross-team forum, but some hesitation about reframing the Platform team as "infrastructure" since that might be overly narrow.

## Next Steps
I will cancel the practice stand-up and schedule the weekly practice-wide session proposed above. I'll invite engineers to opt-in to the updated platform@ group corresponding to the practice events.

#### Exceptions
We'll defer the question of renaming the team for now. This maintains the potential ambiguity, but at least doesn't appear to exclude in-scope responsibilities like tooling.
